# Site settings
title: J.-P. de la Croix
email: ajpl.delacroix+website@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: ffd234
  secondary: 3d454f
  secondary-dark: 292f36
  secondary-light: f8f8f9
  tertiary: 2ebbe5

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/jdelacroix
  - title: twitter
    url: https://twitter.com/jpdelacroix
  - title: linkedin
    url: https://www.linkedin.com/in/ajpldelacroix
  - title: stack-overflow
    url: https://stackoverflow.com/users/3661195

# Postal address (add as many lines as necessary)
address:
  - line: Graduate Research Assistant
  - line: Ph.D. Candidate
  - line: Electrical and Computer Engineering
  - line: Georgia Institute of Technology

# Build settings
markdown: kramdown
permalink: none

gems:
  - jekyll-sitemap
